server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: conector1Messages
          group: transformacionesIntakeGroup
        output:
          destination: transformacionMessages
      default: 
        contentType: application/json

transformacion:
  class: transformacionMayuscula
