//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.10 at 07:25:48 PM UYT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://clienteFinalSOAP/personas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package clientefinalsoap.personas;
