spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: transformacionPaso2MessagesS1
          group: transformacionesPaso3IntakeGroupS1
          consumer:
            maxAttempts: 1
        output:
          destination: transformacionPaso3MessagesS1
          consumer:
            maxAttempts: 1



transformacion: 
  xslt:
    s1:
      paso1: xslt/minuscula.xsl
      paso2: xslt/mayuscula.xsl
      paso3: xslt/minuscula.xsl
      paso4: xslt/mayuscula.xsl
      paso5: xslt/minuscula.xsl