spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/enriquecamejo/prototipo.git
          search-paths:
              - "configuraciones/{application}"
