#server:
#  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: conector1MessagesS1
          group: transformacionesPaso5IntakeGroupS1
        output:
          destination: transformacionMessagesFinalS1
      default:
        contentType: application/json

#transformacion:
#  class: transformacionMayuscula

transformacion: 
  xslt:
    s1:
      paso1: xslt/minuscula.xsl
      paso2: xslt/mayuscula.xsl
      paso3: xslt/minuscula.xsl
      paso4: xslt/mayuscula.xsl
      paso5: xslt/minuscula.xsl